### PR TITLE
[FINAL] Added a coroutine with a timestep

### PR DESCRIPTION
**Pull request by alexey-dc**
Added it to moai Core for now. We can consider making a mindsnacks extension, and adding custom classes there. We can merge this in for now to get over our issues with actions, and refactor later...

### CODE REVIEW

**Comment by aab29** [comment]
Cool!  :snowflake:   For reference, here are two problems I'm hoping this change would allow us to fix:

```
local function createPowerupShrinker()
    local powerupIcon = Sprite.spriteWithName("shrinker.png")
    powerupIcon:setAnchorPoint(0.5, 0.395)

    local pulseInAction = ease(scaleTo(powerupIcon, 0.375, 0.5), MOAIEaseType.SMOOTH)
    local pulseOutAction = ease(scaleTo(powerupIcon, 0.375, 0.9), MOAIEaseType.SMOOTH)
    local pulseLoop = loop(sequence(pulseInAction, pulseOutAction), 6) -- I think there's something wrong with looping loop()s.  pulseLoop only seems to cycle once per idleAction cycle.

    local spinAction = rotationBy(powerupIcon, 4.5, -360.0)
    local cycleAction = spawn(spinAction, pulseLoop)

    powerupIcon.idleAction = loop(cycleAction):start()

    return powerupIcon
end
```

:arrow_up: In this code, `pulseLoop` only cycles once per cycle of `powerupIcon.idleAction`.
:arrow_down: This code just crashes in Lua when it tries to create the `spawn`.

```
local function createPowerupFirework()
    local powerupIcon = Sprite.spriteWithName("firework.png")

    local pulseInAction = ease(scaleTo(powerupIcon, 0.375, 0.5), MOAIEaseType.SMOOTH)
    local pulseOutAction = ease(scaleTo(powerupIcon, 0.375, 0.9), MOAIEaseType.SMOOTH)
    local pulseAction = sequence(pulseInAction, pulseOutAction)

    local spinAction = rotationBy(powerupIcon, 0.75, -60.0)
    local cycleAction = spawn(spinAction, pulseAction) -- It crashes here.  :-(

    powerupIcon.idleAction = loop(cycleAction):start()

    return powerupIcon
end
```

The second one crashes on line 61 in ActionHelpers:
`action:setAttrLink(MOAITimer.ATTR_TIME, spawnAction, MOAITimer.ATTR_TIME)`
It crashes for this reason:
"attempt to call method 'setAttrLink' (a nil value)"

:moneybag: A zillion dollars to anyone who can solve these problems. :money_with_wings:

**Comment by aab29** [comment]
Also, if it solves those problems, I'll merge it.  :wink:

**Comment by JayAustria** [comment]
Code looks good. New Timer Coroutine will def. fix the second bug. We just need to switch the MOAICoroutine out with the MOAITimerCoroutine. As far as I know :shipit: but I'll let Alexey take a stab at the first bug and the merge

**Comment by alexey-dc** [comment]
Solves the second problem, first problem is solved by removing the attribute link from spawn to loop :(. See
https://github.com/mindsnacks/Ahu/pull/83

**Comment by aab29** [comment]
:thumbsup: :sheep:

**Pull request merged**
