### PR TITLE
Xcode 12 GM 1.28.1

### PR DESCRIPTION
**Pull request by kthotav**
Change deployment target.

### CODE REVIEW

**Comment by jpoka** [comment]
@stevenmah I think the changes in this PR make sense to go directly into `mindsnacks-dev`. Just double checking that.

**Comment by stevenmah** [comment]
I think we should hold it in this branch for now since `mindsnacks-dev` is shared across all three products. Alternatively, we can merge and then the other apps just don't bump. Thoughts @jerelevine and @antonmorant?

**Comment by jerelevine** [comment]
No strong opinion here

**Comment by stevenmah** [comment]
Let's hold off on merging just in case until we confirm everything is working fine, with these changes.

**Comment by kthotav** [comment]
I placed a hold on this for now

**Comment by antonmorant** [comment]
I'm fine with merging to master. We bump moai so rarely that it's unlikely
we'd pick up this change by accident rather than deliberately.
Fine with waiting until it's confirmed to be working.

**Review by jpoka — APPROVED** [review]

**Pull request merged**
