### PR TITLE
Fixed building problems for android version

### PR DESCRIPTION
**Pull request by tonidero**
Fixed building problems for android version. Removed untz library

### CODE REVIEW

**Comment by NachoSoto** [comment]
Oops. The checkout file is not supposed to be commited. We should add it to .gitignore.

**Comment by NachoSoto** [comment]
Looks good!

**Comment by jeiting** [comment]
Yep, build for android works now. We can merge it if its ready.

**Comment by tonidero** [comment]
I think it is, at least it seems to work. Whenever you're ready we can merge

**Pull request merged**
