### PR TITLE
[FINAL] Added line spacing support in MOAIFreeTypeFont

### PR DESCRIPTION
**Pull request by JayAustria**

### CODE REVIEW

**Comment by aab29** [comment]
@JayAustria does this still need to be merged in for Sunset?  :sun_with_face: :arrow_down:

**Comment by JayAustria** [comment]
@aab29 Yes pls. I was thinking I could look into converting my text stuff over to the new text rendering so that we wouldn't need this merge, but I don't think we have the time to beef up the new text rendering to match my other tech needs. Plus, line spacing in a regular ol' multi-line label is nice to have anyway.

**Comment by aab29** [comment]
Good deal.  :shipit:

**Comment by aab29** [comment]
Note: Apparently this broke `MOAITextRenderer` in one place.  I just fixed it by telling `MOAITextRenderer` to use `0.0f` for the `lineSpacing` and pushed the change.  Feel free to add better support for `lineSpacing` in `MOAITextRenderer` if/when we have time...

**Comment by JayAustria** [comment]
@aab29 Thanks for the notice! Also, just a friendly reminder that since this checkin changes the argument count for the label constructors, we might also want to get https://github.com/mindsnacks/Ahu/pull/340 merged in

**Pull request merged**
