### PR TITLE
Added realloc() call to MOAIFreeTypeFont

### PR DESCRIPTION
**Pull request by IkeBart**
I replaced the calls to `ResetBitmapData()` and `calloc()` with calls to `realloc()` and `memset()` in `MOAIFreeTypeFont::InitBitmapData().`

### CODE REVIEW

**Comment by NachoSoto** [comment]
Does ResetBitmapData do anything else?

**Comment by IkeBart** [comment]
> Does ResetBitmapData do anything else?

Here is the current code of `MOAIFreeTypeFont::ResetBitmapData()`:

``` c++
void MOAIFreeTypeFont::ResetBitmapData(){
    if (this->mBitmapData) {
        free(this->mBitmapData);
        this->mBitmapData = NULL;
    }
}
```

This method calls free on the member variable `mBitmapData` and sets it to NULL if the value of the variable is nonzero.  It is called in the destructor of `MOAIFreeTypeFont`.

**Comment by NachoSoto** [comment]
Does realloc work if the original pointer is NULL?

**Comment by NachoSoto** [comment]
```
If ptr is a null pointer, realloc() behaves like malloc() for the specified size.

If ptr does not match a pointer returned earlier by calloc(), malloc() or realloc() or if the space has previously been deallocated by a call to free() or realloc(), the behaviour is undefined.
```

So the first line answers my question: it's okay.
And the second thing should not happen since we're setting `mBitmapData` to NULL``` when freeing, and also in the constructor.

**Comment by NachoSoto** [comment]
:shipit:

**Comment by aab29** [comment]
:thumbsup: :shipit:

**Pull request merged**
