### PR TITLE
Updated SQLite

### PR DESCRIPTION
**Pull request by NachoSoto**

### CODE REVIEW

**Comment by NachoSoto** [comment]
I'm making sure all our tests pass before we merge this.

**Comment by NachoSoto** [comment]
@msolomon are you good with this then?

**Comment by msolomon** [comment]
Could we change the directory name? `3rdparty/sqlite-3.6.16/` will be confusing

**Comment by NachoSoto** [comment]
Oh I didn't realize that. I'll move it.

**Comment by NachoSoto** [comment]
Done

**Comment by msolomon** [comment]
:thumbsup: just be sure to update your build process to handle the new directory

**Pull request merged**
