### PR TITLE
[FINAL] Release texture memory in dealloc of MOAITexture

### PR DESCRIPTION
**Pull request by tonidero**
This was a good find. It was worth it to spend the day :)

### CODE REVIEW

**Comment by aab29** [comment]
Unbelievable.

How is this possible?  Releasing texture memory from inside Moai seems to work.  Does it just not clean up after itself when you destroy the Moai instance?

At any rate, nice find, @tonidero !

**Comment by NachoSoto** [comment]
It does, and textures are deallocated, but the heap memory inside is
not freed automatically.

**Comment by aab29** [comment]
Ah--that explains it.  (facepalm)

**Comment by jeiting** [comment]
Do not shipit. This is redundant code.

**Comment by aab29** [comment]
I thought something seemed off.  I retract my shipit for now.  (Although it was still a nice find.)  We should continue investigating.  :goat: :mag:

**Comment by tonidero** [comment]
Hmm they did this on the original moai a few months ago. Seems the problem is only when you load the textures but not create them (start playing). Then it doesn't frees the memory. https://github.com/moai/moai-dev/pull/805

**Comment by jeiting** [comment]
That code shouldn't have been merged to MOAI mainline, hence why we don't pull from them.

**Comment by NachoSoto** [comment]
Solved in #76.

**Pull request closed without merging**
