### PR TITLE
[FINAL] Compile SQLite with temp files off by default

### PR DESCRIPTION
**Pull request by msolomon**
Fixes the notorious "could not open database file" SQLite bug.

My suspicion is that SQLite was trying to open a temporary file somewhere that it didn't have write access to and gave an error message without much detail.

### CODE REVIEW

**Comment by NachoSoto** [comment]
Wow. Nice find! So we're sticking with MOAI's SQLite? fine with me for the time being.

**Comment by NachoSoto** [comment]
So this fixes it for sure? :)

**Comment by msolomon** [comment]
Ha. It certainly has so far, and for a more understandable reason than before.

I read the section on sqlite temp files carefully, and it looks like there are a couple of temporary files you can't prevent it from creating (journal and WAL, as I recall). I'll run a bunch of SQL in a loop today to ensure that they're getting created and that it doesn't crash at that time.

**Comment by NachoSoto** [comment]
That would explain things... the SQLite in Android is probably compiled like this.

**Pull request merged**
