### PR TITLE
[FINAL] Optimized ProcessOptimalSize.

### PR DESCRIPTION
**Pull request by kstenerud**
There are two main parts to this PR:
1. Debug. This basically exposes the `DEBUG` compiler macro to LUA via MOAISim. Whatever compiler setting moai was built with is what MOAISim will return when you call `MOAISim.isDebug()`. This is not something we expect to use often, and no games should ever refer to it directly.
2. Optimal text sizing. This first checks the maximum font size for a fit, and then begins a binary search of the font size range. roundToInteger is no longer needed since granularity performs the same function and more. So if you pass in sensible defaults (at least for the max font size), you should see a sizable performance boost over the old code in the common case.

### CODE REVIEW

**Comment by kstenerud** [comment]
There is one thing I'd like to ask everyone's opinions on:

If the system is unable to fit the text using the font size range you specified, it currently returns the minimum font size. As a result, you won't know if the text actually did fit, and happened to do so at the smallest font size, or if it simply didn't fit at all.

One option would be to return a special value (like a negative value) to indicate that it couldn't fit.
The other option would be to just ignore the problem. If the text doesn't fit, we'll see it in the game.

**Comment by NachoSoto** [comment]
The other option would be to throw an exception, but maybe only #if DEBUG. That would allow us to catch this problem quickly while developing, but a sane default of "it almost fits" in Release?Nacho Soto

**Comment by kstenerud** [comment]
In that case I'd rather assert in LUA land, as an exception would crash Achilles.

**Comment by NachoSoto** [comment]
We can catch that particular exception in Achilles. How would you know in LUA if it's DEBUG or RELEASE mode?Nacho Soto

**Comment by kstenerud** [comment]
Just so long as we can get the LUA stack trace leading up to the exception...

The alternative would be to return a special code from C++ depending on whether it's in debug or release mode, and have the LUA side react to that.

**Comment by jeiting** [comment]
Mmmmmm. Making it crash in debug whenever the label doesn't fit might be terrible. Is there an obvious recourse for programmers? Will it be something that "doesn't happen for me" but as soon as we pass it off to QA its crash town?

**Comment by kstenerud** [comment]
At the very least I want to let LUA decide what to do when it doesn't fit. If we can accomplish that with C++ exceptions, great. Otherwise I'll just add another special return code.

**Comment by kstenerud** [comment]
@jeiting It would be the other way around: It crashes on a debug build but on release it just returns the minimum font size you asked for so that at least it doesn't crash.

**Comment by kstenerud** [comment]
Perhaps we could also make #DEBUG available to LUA? The more of this decision process that exists on the LUA side, the better.

**Comment by NachoSoto** [comment]
I wouldn't pass DEBUG to LUA, the least games know about the compilation environment the better, because the games arenmt compiled with the binary.Nacho Soto

**Comment by NachoSoto** [comment]
We can get the LUA trace that led to the exception.

I think the best resource for developing games is knowing asap when something went wrong in a way that can't be ignored.
Nacho Soto

**Comment by kstenerud** [comment]
In this case it wouldn't be the games knowing about the environment (which is a bad idea), but rather the LUA support library (in this case the font render engine, LUA side) deciding.

**Comment by jeiting** [comment]
misclick

whoops

**Comment by kstenerud** [comment]
Another benefit of exposing debug is that we can disable the profiler from the LUA side as well, so that instead of crashing on a release build, it just ignores requests to profile.

**Comment by aab29** [comment]
It seems a lot easier to me to pass a special value (say, `nil`) when the text won't fit.  Fewer moving parts, and we know immediately when something went wrong.  :computer: 

I'd be OK with an exception too (as long we get a Lua stacktrace), but judging from the length of this conversation, it likely is more trouble than it's worth.  :melon: 

In other news, nice work on this @kstenerud !  Yeah, `roundToInteger` didn't make sense anymore.  Can we expect some performance gains from this?  :speedboat:

**Comment by NachoSoto** [comment]
I'm fine with always crashing when this happens, in release too.Nacho Soto

**Comment by kstenerud** [comment]
I'm not fine with it always crashing in release. We're dealing with variable length text, and we don't have the resources to test every single concept in every single game.

**Comment by kstenerud** [comment]
@aab29 The new code will check the max font size first and then begin a binary search, whereas the old code would converge towards the max font size, so if you pick a sensible max font size, you should see a considerable performance boost.

**Comment by NachoSoto** [comment]
I was answering @aab29: "It seems a lot easier to me to pass a special value (say, nil) when the text won't fit.". What do we do in LUA if it returns nil?

**Comment by kstenerud** [comment]
On the LUA side calling ProcessOptimalSize will repeatedly return nil until it has converged on the optimal size, at which point it will return that font size.

My proposal is to have the C++ side return a negative value in the case where it was unable to fit within the min/max font size. Then, on the LUA side, FontRenderEngine would catch the negative value and decide how to handle it (assert if in debug mode, return min font value on release).

**Comment by aab29** [comment]
To answer "What do we do in Lua if it returns `nil`?"  (I actually realized it can't be `nil`, but it could be a negative number or something.) :  

I think the Lua side of the `FontRenderEngine` should catch the special value, `print()` an error message, and then return `nil` to the game code.  Unless the game code handles it, this will just make the app crash in Lua.  Yes, this will happen in release too, but the game devs will know if text not fitting is likely for their particular situation, and they can tell their games not to crash if that's appropriate.  :bread: 

Taking different courses based on whether a build is debug or release sounds good in theory, but based on previous experience, I predict it will cause confusion and give us a false sense of security.  :unlock:

**Comment by kstenerud** [comment]
If we let it return a nil font size to game code, it opens us to two risks:
1. The code that creates the label could be far removed from the code that calls the optimal size calculation.
2. If we return a nil font size to game code, we'll forever be running the risk of a particularly long word crashing the games rather than just looking funny.

**Comment by kstenerud** [comment]
I think that taking different courses based on debug/release is OK so long as the debug course is far more strict than the release course.

In this case, debug would crash, and release would return a font size that's too big. The end user experience would be something that looks funny, but at least it doesn't crash.

**Comment by aab29** [comment]
Even with the risks that Karl describes, I still think it's better to let the games handle it.  :card_index: 

I can recall many occasions where confusion over whether a build was "debug or release" has caused us to overlook bugs or has made it impossible for us to replicate the bugs that QA tracks down.  :rooster: 

It's actually not a huge deal to me.  :cookie:   If you're confident you can pull it off, just do it.  But it seems overly complicated and confusing, so if it were up to me, I wouldn't.

**Comment by kstenerud** [comment]
OK this should be good to go. Everything is set up such that the LUA side can decide how to handle failure, and has all of the tools necessary to do so.

**Comment by aab29** [comment]
Looks good to me.  @IkeBart can you please look this over quickly and make sure it makes sense?

:shipit:

**Comment by aab29** [comment]
I think Isaac is away on vacation.  Let's get this merged today so we don't hold up https://github.com/mindsnacks/Ahu/pull/369 .

**Comment by IkeBart** [comment]
I'm going on vacation tomorrow.  I should be back before 2014-01-04.  How do I pull this branch so I can test it on my computer?

**Comment by alexey-dc** [comment]
A little late to this, but my 2 cents on the "what to do when font size range is invalid" issue:

I'm closer to Karl on this. We should be able to catch this in debug, it shouldn't crash for QA or the users. An appropriate return value that can be handled in lua is fine.

IMO having a debug mode for games is totally fine and useful... Even having a global variable called DEBUG in lua can be helpful, but it should probably be set by the host so we don't forget to turn it off for release builds.

:shipit:

**Comment by JayAustria** [comment]
Changes look clean :shipit: I'll let Isaac check this out first, though

**Comment by aab29** [comment]
@IkeBart `git checkout  feature/optimal-size`?

If you need help...
`git checkout --help`
`git pull --help`
`git remote --help`

If you're having trouble checking it out, just look over the diff and make sure everything makes sense to you.  :tram:

**Comment by IkeBart** [comment]
I was able to checkout this `feature/optimal-size` and test it out.  Everything looks good.  :shipit:

**Pull request merged**
