### PR TITLE
[WIP] Introduced a weird fix that seems to make the issue go away

### PR DESCRIPTION
**Pull request by alexey-dc**
Dafuq... no idea why this fixes it... any thoughts?

### CODE REVIEW

**Comment by kstenerud** [comment]
MOAINodeMgr contains some of the scariest code I've seen in a long time.

From the looks of it, there's no actual need to get node->mNext and store in a temp location because there's nothing that could ever modify mNext (MOAINode doesn't even touch it except during construction).

It seems that the main difference is WHEN a node gets its state set to STATE_IDLE. In the old code, all nodes will be switched to STATE_ACTIVE as you loop through the first time, and then will be set to STATE_IDLE in the second loop.

With these changes, the nodes will be set to STATE_IDLE as you loop through, which will affect any other nodes that have links to nodes that have already been looped through. This is incredibly scary because a node's behavior in this loop depends entirely on whether a node it's linked to is earlier or later in the list! It's a miracle this code ever worked at all...

According to the code:

```
enum {
    STATE_IDLE,         // not in list
    STATE_ACTIVE,       // in list but not scheduled
    STATE_SCHEDULED,    // in list and scheduled
    STATE_UPDATING,     // currently being updated
};
```

So, STATE_IDLE means "not in the list" (wtf). But if any linked nodes get activated through code paths from DepNodeUpdate, they'll get thrown onto the list we're currently iterating through, because MOAINode::Activate and ActivateOnLink call MOAINodeMgr::InsertXYZ functions. So this means that under certain circumstances, some nodes would have their update routine called twice. This kind of shit is exactly what the standard C++ container classes were designed to avoid, but I digress...

End result: By setting to IDLE before iterating through the entire list, some nodes may run their update twice, which means that this change is probably covering up the underlying issue, because in your test case, the "bad" node is earlier in the list than the node it's linked from. If it happened to be later in the list, the bug would come back.

**Comment by alexey-dc** [comment]
My intuition was that setting things to STATE_IDLE would mean they don't get updated. However, If I remove the STATE_IDLE and Release() calls altogether, the bug comes back in pretty much the exact same form as with the base code (I would expect a non-idle state to actually receive the updates every frame or something). I tried all permutations of setting up attribute links in my tests. W/o this fix, the order is in fact significant. With this fix, it never seems to break.

I do think that optimization issues would be secondary to functional issues - i.e., having nodes get updated twice is not toooo bad right now. But you're right, with this kind of fix, the underlying issues could bite us in the ass at any time.

For now I'm writing the Paragraphs game with this fix, and no issues seem to crop up, but maybe I'll run into a test that will help reveal the deeper issues. If not, I guess reading this crappy code is the only thing that can help us really resolve the foundation of the bug. I think today I'll finish some more game code, and give this another go tomorrow.

**Comment by kstenerud** [comment]
Considering how nasty and tangled the code is to begin with, I'm not averse to this fix, but we should probably leave in a note about the further concerns the fix raises.
A node running its update twice is not a huge issue per se. I'm more worried about non-idempotent methods being called during the update (I don't know if any actually are).

**Comment by jeiting** [comment]
No.

Please don't just monkey patch something you don't understand in code we don't really understand.

**Comment by NachoSoto** [comment]
That would be the beginning of the end. A bug we haven't found a fix for is better than another bug we create for trying to fix the original one without understanding the problem. That's just making things worse.

**Comment by alexey-dc** [comment]
I'm not really sure the authors understand the code any better than we do. Like Karl said, it's a miracle this code ever worked at all :-D. Also, it has known bugs, and we do know the properties of the initial code and the fix. Not understanding the code is really a property of the code itself, you can't reason formally about something so entangled.

That being said, I'll try to make some formal assertions about the code tomorrow so we can be reasonably secure in whatever fix we end up going with (maybe I'll discover a better way to fix it through the formal reasonings, but worst case we'll have to rely on tests, like I'm currently doing).

I should also note that I launched a few of our games with this fix, and there were no apparent issues with them.

**Comment by NachoSoto** [comment]
If you can reason why this solution is the valid one, then we can merge it.
Just read your own title for this Pull Request: `Introduced a weird fix that seems to make the issue go away`.

**Comment by alexey-dc** [comment]
It's mostly marked as WIP because I do want to investigate any repercussions this fix might have, then I'll be able to say "yes...ish" to being able to reason why this solution is valid.

There's two reasons I consider this fix to be weird. Number one is the comment I deleted: "TODO: fix this later". Number two is the fact that I would expect something not being flagged as IDLE in a dynamic simulation to receive updates every timestep, thus forcing the updates. In fact, I see the opposite behavior. It's a hint that setting something as IDLE isn't as simple as the name might imply, and does more things in the system, and along with that TODO, makes me feel like like I'm stacking one of the last Jenga pieces. But so far, this code works better than the old code and does not exhibit any bugs.

**Comment by jeiting** [comment]
The awkward part where I ask if anyone has even looked at upstream moai.

**Comment by jeiting** [comment]
```
I'm not really sure the authors understand the code any better than we do.
```

patrick@ziplinegames.com

**Comment by alexey-dc** [comment]
Good point, I'll ask him tomorrow.

AFAIK, we've deviated quite a lot from upstream moai... not sure if anyone wants to merge their stuff back in, though I did consider looking before attempting to find the issue. Decided against it for now :-D.

**Comment by adamvillalobos** [comment]
I can ask patrick about this tomorrow.

**Pull request closed without merging**
