### PR TITLE
Fixed leaks in MOAIFreeTypeFont

### PR DESCRIPTION
**Pull request by NachoSoto**
Because of all the duplicated code in the file I had to also duplicate all these lines.

### CODE REVIEW

**Comment by aab29** [comment]
Looks good to me.  @IkeBart does this look OK?

:shipit:

**Comment by IkeBart** [comment]
Yes, it looks good to me too.

**Comment by NachoSoto** [comment]
Would you guys mind mentioning me on PR so that I can review them from now on? :)

**Comment by NachoSoto** [comment]
Bump.

**Comment by NachoSoto** [comment]
I'll take that as a yes?

**Comment by aab29** [comment]
Guess I should've tested this more before merging.  Every third question or so in Waves, I'm now getting an EXC_BAD_ACCESS in the `FT_Done_Glyph` call in the `deleteGlyphArray()` call in `RenderTextureSingleLine()`.  @NachoSoto is it possible we're deleting too much here?  If I comment out that particular delete call, it stops crashing, but every label renders only one character, even if there are more in the string.  I'm going to revert this PR until we can figure out why it's crashing.

**Comment by NachoSoto** [comment]
Can you share the trace?

**Comment by aab29** [comment]
Sure:

delete-glyph-array-crash

**Comment by aab29** [comment]
@IkeBart Could you please remove the repeated code in this file when you have a chance?  Thank you.

**Pull request merged**
