### PR TITLE
[FINAL] MOAIFreeTypeFont: fixed clipped letters when using returned value of processOptimalSize

### PR DESCRIPTION
**Pull request by IkeBart**
Isaac wrote a description in here, but it was confusing out of context (Sorry, Isaac!).  So I (Aaron) will try to explain.

When we first started using `MOAIFreeTypeFont` there were lots of problems with text getting cut off.  :hocho:   After several revisions we've eliminated almost all of them, but very rarely, there's still a case where `optimalSize()` returns a value that is too big, and one or two pixels will get cut off on either side.  Isaac hasn't been working on text in a few months, but when I isolated this problem and sent him a repro case, he was kind enough to come up with a fix.  I've spent all morning testing it in a test game I wrote and running it through all of our actual games.  I'm confident that it fixes the problem.

Here are some before and after screenshots from Up:
domestic_before
domestic_after

And Squares:
rescind_before
rescind_after

Thanks for your help, Isaac!  :cake:

### CODE REVIEW

**Comment by alexey-dc** [comment]
Awesome! Thanks Isaac! :shipit:

**Comment by NachoSoto** [comment]
Nice, the result of an underflow? I guess it makes sense.

**Comment by aab29** [comment]
_(bump)_ Anyone else want to look this over?  Would be awesome to get it in this week.  :smile_cat:

**Comment by NachoSoto** [comment]
Feel free to open a PR to CoreMS with this :)

**Pull request merged**
