### PR TITLE
Fixed issues with new lines that caused runtime errors in MOAIFreeTypeFont

### PR DESCRIPTION
**Pull request by IkeBart**
I fixed issues regarding newline characters in strings so that the whole string gets displayed and there aren't any errors when freeing the glyph array.  I also fixed the handling of the word break mode WORD_BREAK_CHAR and the case in WORD_BREAK_NONE where the token is too long to fit on a single line.

I did an analysis with the Leaks Instrument and found nothing on the Leaks graph on all six runs.  The Allocations graph shows a spike during loop where MOAITextRenderer::_render() is called up to 5000 times.  After the spike, the graph falls and settles at a level between 15 and 20 MB.  If the loop is short (as in 50 times), the graph settles near the maximum, but a lower number of live bytes.

### CODE REVIEW

**Comment by NachoSoto** [comment]
Can you post a picture of the total allocations graph? For what you're describing it seems like not all the memory is being freed?

**Comment by IkeBart** [comment]
How do I post a picture in these comments?  I know how to take a screenshot, but not how to post the screenshot here.

**Comment by NachoSoto** [comment]
You can simply drag and drop it to the comment box :)

**Comment by IkeBart** [comment]
This is one of the runs where I ran the loop containing MOAITextRender::_render() 5000 times.
image

This is one of the runs where the I ran the loop a much smaller number of times.  I think I ran it either twenty or fifty times.
image

This is the most recent of the runs where I ran the loop 1000 times.
image

**Comment by NachoSoto** [comment]
There's your leak :) The leak instrument doesn't detect it because it's most likely a cycle, _or_ there are still references to that memory.

**Comment by IkeBart** [comment]
I gathered some data to support the hypothesis that what appeared to be leaks were uncollected MOAI objects, fixed by garbage collection.

| Loop Repetitions | Peak Memory Usage | Stable Level | Level After Garbage Collection |
| --- | --- | --- | --- |
| 20 | 10.99 MB | 6.70 MB | 6.58 MB |
| 50 | 12.01 MB | 7.69 MB | 6.58 MB |
| 100 | 13.62 MB | 9.39 MB | 6.62 MB |
| 200 | 17.02 MB | 12.65 MB | 6.61 MB |
| 400 | 18.93 MB | 14.62 MB | 6.61 MB |
| 800 | 28.13 MB | 10.59 MB | 6.59 MB |
| 1600 | 53.91 MB | 21.11 MB | 6.64 MB |
| 3200 | 105.18 MB | 13.78 MB | 6.74 MB |
| 5000 | 162.99 MB | 15.42 MB | 6.77 MB |

The cache in the Lua program held a maximum of twenty props in all of the runs I did.  The dimensions of the texture to render were 48 pixels wide by 128 pixels high.  The font used was "NeutraTextBold.otf" at size 24.   After getting the stable level, I clicked in the upper-left corner to call `MOAISim.forceGarbageCollection()` to get the level after garbage collection.

Here's a screenshot of the run with 20 loop repetitions.  The final stage around the 29 second mark at 4.61 MB came after I collected garbage when there were no props on the screen.

image

200 loop repetitions.
image

800 loop repetitions.
image

5000 loop repetitions.
image

**Comment by IkeBart** [comment]
I modified the method `handleTouches :( NSSet*)touches :( BOOL )down` in MoaiView.mm to call AKUFinalize() when touching in the lower right corner on the simulator.  This caused a bad access crash on Xcode.  When I ran Instruments, I got the following reports.

For 5000 repetitions, final memory usage of 5.48 MB.
image

For 500 repetitions, final memory usage of 5.35 MB.
image

For 50 repetitions, final memory usage of 5.35 MB.
image

**Comment by IkeBart** [comment]
I did another series of tests with this function:

``` lua
local function numberPropLoop(times, waitTime)
    local numberImage = MOAIImage.new()
    numberImage:load("numbers.png")

    local numberTexture = MOAITexture.new()
    numberTexture:load(numberImage)

    local tileDeck = MOAITileDeck2D.new()
    tileDeck:setTexture( numberTexture )
    tileDeck:setSize(8, 8)
    tileDeck:setRect(0, 32, 32, 0)
    tileDeck:setUVRect(-0.5, -0.5, 0.5, 0.5)

    if ( type(waitTime) == "number" ) then
        print(string.format("Waiting %f units of time before doing the loop", waitTime))
        local timer = wait( waitTime )

        print(string.format("timer == %s", dump(timer) ) )
        repeat coroutine.yield() until not timer:isBusy()

        print("The loop begins...")

    elseif not ( type(waitTime) == "nil" ) then
        print(string.format("Expected number for waitTime, got %s", type(waitTime))  )
    end

    for i = 1, times, 1 do
        local newProp = MOAIProp2D.new()
        newProp:setDeck(tileDeck)
        newProp:setIndex( i )

        local xLoc = off.x + (((i-1) * 32) %  221 )
        local yLoc = off.y + (((i - 1) * 6) % 450 )

        newProp:setLoc(xLoc, yLoc)

        addToCache( newProp )
    end

    registerTouchCallback(
        function(x, y)
            --if ((x < 10) and (y < 10) ) then
                print("Schedule a manual garbage collection...")
                MOAISim.forceGarbageCollection()

            --end
        end
    )

end
```

The call to this method looks like `numberPropLoop(5000, waitTime)`

It does not use any MOAIFreeTypeFont methods.  What it does do is create a lot of props with the same deck and use the most recently added props.  Any old props get deleted.

I did some testing with Instruments.

| Loop Repetitions | Peak Memory Usage | Stable level | Level after GC |
| --- | --- | --- | --- |
| 5000 | 10.30 MB | 5.97 MB | 5.21 MB |
| 10000 | 10.78 MB | 6.45 MB | 5.26 MB |
| 20000 | 11.95 MB | 6.51 MB | 5.26 MB |
| 40000 | 20.77 MB | 6.56 MB | 5.26 MB |
| 80000 | 38.45 MB | 6.20 MB | 5.21 MB |

This time, I did the gathering of the largest number loop repetitions first, then worked down.  If there is a memory leak, I don't know how to fix it.

5k repetitions:
image

20k repetitions:
image

80k repetitions:
image

**Comment by aab29** [comment]
Isaac's tests seem to indicate that Moai's memory usage fluctuates (probably because of some cache, or the Lua runtime itself).  Without a standard baseline, we have no way to figure out if anything's leaking.  Is there a good way to isolate the memory usage of `MOAIFreeTypeFont`?  If not, I'd suggest merging this PR so Isaac can concentrate on the next thing.  We'll keep monitoring for leaks, and if we find any, we'll fix them.  :umbrella:

**Comment by NachoSoto** [comment]
So does LUA show a similar behavior in memory usage without using `MOAIFreeTypeFont` at all? I guess that test is kind of the same as isolating the memory usage of the font part :P

**Comment by aab29** [comment]
Yep, that's what Isaac's most recent test demonstrates.  Well--for Moai at least; we can't be sure it's because of Lua.  The program he used has a loop in it that creates a prop, adds it to the screen, and removes it.  After the loop finishes, he forces garbage collection of everything.  `MOAIFreeTypeFont` is not involved anywhere.  The memory usage after garbage collection for 5,000 iterations is less than that for 10,000 iterations, but equal to that for 80,000.  The tests he ran previously that _do_ involve `MOAIFreeTypeFont` do the same thing, except that they render textures and display them on the props before removing them.

**Pull request merged**
