### PR TITLE
[FINAL] Fix Android L build

### PR DESCRIPTION
**Pull request by tonidero**
This was crashing the app on startup on the latest version of Android L.

I don't really know why it worked before without this actually. But this seems to work for both old OS and the latest preview of Android L

### CODE REVIEW

**Comment by jeiting** [comment]
This must have been part of Android's libraries but was removed?

**Comment by tonidero** [comment]
Yup I was checking it and I removed it a long time ago, my mistake. Strange that the problem emerges now.

**Comment by jeiting** [comment]
Now we need to update CoreMS :)

**Comment by tonidero** [comment]
I can do that :)

**Pull request merged**
