### PR TITLE
Fixed building problems for iOS version

### PR DESCRIPTION
**Pull request by IkeBart**
In this commit, I fixed the iOS project build errors introduced by #39 and some other commits.  I removed the USE_UNTZ preprocessor directive from the project file.  I also added the USE_UNTZ preprocessor directive as a condition for compiling the source of the UNTZ files.  In the case of `MOAIAppIOS`, `MOAIGameCenterIOS` and `MOAIMoviePlayerIOS`, I added back the destructor definitions that were removed by a commit that dealt with Automatic Resource Counting.

### CODE REVIEW

**Comment by NachoSoto** [comment]
Great! Thank you @IkeBart, I was getting linker errors and looks like this should be the fix!

**Comment by NachoSoto** [comment]
It works! Thank you. Merging this.

**Comment by aab29** [comment]
:+1: Nice work, Isaac!

**Comment by NachoSoto** [comment]
@aab29 you're right, the commit is here, but then it's reverted (I didn't realize that change wasn't in the diff).

**Pull request merged**
