### PR TITLE
feature/misc clean up

### PR DESCRIPTION
**Pull request by jpoka**
- Misc. clean-up to see how it goes and if we want to do more going forward.
- Remove unused variables
- Remove `MOAIMoviePlayerIOS`
- Remove `MOAIMoviePlayerAndroid`
- Remove movie player samples
- Remove visual studio related directories

### CODE REVIEW

**Comment by aab29** [comment]
@jpoka Looks like a great idea! 💡👏  Hoping to do a proper review on this when I can, but in case I don't get the chance... one thing to watch out for off the top of my head is compiling this on Android for *both* `geonosis` and `pegasus`.  🪐🦄  I can't remember for sure, but I think that one of them uses `CMakeLists` and the other does not, so we need to be sure they're both working.  🔄🔄

**Review by AlTavares — APPROVED** [review]
LGTM

**Comment by AlTavares** [comment]
Should we merge this?

**Review by aab29 — APPROVED** [review]
I finally had a chance to test this on Elevate, and it's compiling and running fine both on Android and on iOS.  ✅✅ Sorry for the delay!  I think it's fine to merge this in now.  :shipit:

**Pull request merged**
