### PR TITLE
[FINAL] optimal size clean up revert

### PR DESCRIPTION
**Pull request by JayAustria**
During https://github.com/mindsnacks/moai-dev/pull/47, an attempt was made to clean up a small amount of duplicated code. It turns out that the second occurrence of the code wasn't actually redundant so this reverts the change made in PR 47. (Details: the variable `lineHeight` was assumed to never change within the do while loop so was moved out...turns out the `FT_Set_Char_Size` made non-obvious changes to `face` per iteration)

### CODE REVIEW

**Comment by aab29** [comment]
I'm kinda' confused.  :cactus: Is it the exact same code?  If so, is it possible to move it into a separate function?

**Comment by kstenerud** [comment]
Nasty code, but not our domain. :shipit:

**Comment by JayAustria** [comment]
Its not visible in the diff but right before `lineHeight` is calculated, a `FT_Set_Char_Size` method is called which takes in a handle to `face` and a size and seems to change the return value of (u32)(face->size->metrics.height >> 6)

**Comment by NachoSoto** [comment]
I'm with @aab29, could this be put into a separate function to avoid the code duplication?

**Comment by aab29** [comment]
Cool, looks like the duplicated stuff is gone.  The text will be too small in Bloon (to the point that it's unplayable) without this fix, so I'm going to go ahead and merge it now.  :shipit:

**Pull request merged**
